name: flutter_core
description: Package containing core elements of all apps developed within 
  the company. Designed for internal use only.
version: 0.0.1
homepage: https://github.com/NewGymBuddyApp/flutter_core
repository: https://github.com/NewGymBuddyApp/flutter_core
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
